In [66]:
## Vamshi Medisetty
## Assignment - 4


%logstart      ## To take output log into another file

In [4]:
import numpy as np  # To import numpy


In [68]:
## Question 1
# Part - A
n,p=1,0.5
a = np.random.binomial(n,p,8)
a



array([0, 0, 1, 0, 0, 1, 1, 0])

In [72]:
# Part - B

n,p=1,0.3
b = np.random.binomial(n,p,8)
b


array([0, 0, 0, 0, 0, 0, 1, 0])

In [70]:
# Part - C

n,p=1,0.7
c = np.random.binomial(n,p,8)
c


array([1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
## We observe that the number of times a head is apperaing (Success)
## is increasing as we increase the probability of occurence (biased coin)

In [20]:
## Question 2
## Part - A

n,p=5,0.3
a = np.random.binomial(n,p,80)
a
avg1 = np.average(a)
avg1



1.4624999999999999

In [74]:
## Part - B

n,p=5,0.3
b = np.random.binomial(n,p,800)
b
avg2 = np.average(b)
avg2


1.4412499999999999

In [75]:
## Part - C

n,p=5,0.3
c = np.random.binomial(n,p,8000)
c
avg3 = np.average(c)
avg3


1.4995000000000001

In [20]:
## We observe that three averages are almost same
## We observe that if the probability of success is not changing,
## increasing number of trials, is not having any effect on average
## i.e., average increases, only if probaility of heads (success) is increased

In [3]:
## Question 3
## Section - A
# Prob (X<= 12)

import numpy as np
from scipy.stats import norm
p1 = norm.cdf(12,loc=10,scale=3)
p1

n = norm(10,3)
n.cdf(12)


0.74750746245307709

In [26]:
## Section - B
# Prob (X > 8)

p2 = 1 - norm.cdf(8,loc=10,scale=3)
p2

## We notice that both probabilities p1 and p2 are almost same.
## This is the property of normal distribution, that it is symmetrical over the mean
## Hence we see that both the probabilities almost same

0.74750746245307709

In [28]:
## Section - C
# Prob(|X-10|>2)

p3 = norm.cdf(8,loc=10,scale=3) + (1 - norm.cdf(12,loc=10,scale=3))
p3

0.50498507509384583

In [5]:
## Question  4
## Section - A

import pandas as pd
m =5                   ## Mean
s = 2                  ## Std Deviation
n = 1000               ## Sample Size
a = pd.Series(np.random.normal(m,s,n))
a.mean()

5.068593114439275

In [53]:
## Section - B

m =5                   ## Mean
s = 2                  ## Std Deviation
n = 1000               ## Sample Size
a = pd.Series(np.random.normal(m,s,n))
a.std()

2.0431546777204077

In [52]:
## Section - C

m =5                   ## Mean
s = 2                  ## Std Deviation
n = 1000               ## Sample Size
a = pd.Series(np.random.normal(m,s,n))
a.skew()

## We observe that the skew is negative
## That means, it is left skewed

-0.049832625856911464

In [7]:
## Section - D

m =5                   ## Mean
s = 2                  ## Std Deviation
n = 1000               ## Sample Size
a = pd.Series(np.random.normal(m,s,n))
a.kurt()

## We obseve that the kurtosis is lesser than 3.
## This indicates that distribution is platykurtic

-0.061413054456961325

In [17]:
## Question - 5
## Section - A

import pandas as pd
import numpy as np
import statsmodels.api as sm

wage1 = pd.read_csv("C:/Users/vamsh/Desktop/Python_Stats_Assignment/wage1.csv")
wage = wage1.wage
educ = wage1.educ
r = sm.OLS(wage,educ)
reg1 = r.fit()
reg1.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   wage   R-squared:                       0.764
Model:                            OLS   Adj. R-squared:                  0.764
Method:                 Least Squares   F-statistic:                     1701.
Date:                Sun, 24 Apr 2016   Prob (F-statistic):          7.93e-167
Time:                        22:15:01   Log-Likelihood:                -1386.6
No. Observations:                 526   AIC:                             2775.
Df Residuals:                     525   BIC:                             2779.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
educ           0.4727      0.011     41.247      0.000         0.450     0.495
==============================================================================
Omnibus:                      221.585   Durbin-Watson:                   1.822
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              882.785
Skew:                           1.930   Prob(JB):                    2.02e-192
Kurtosis:                       8.037   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [39]:
## Section - B

wage1 = pd.read_csv("C:/Users/vamsh/Desktop/Python_Stats_Assignment/wage1.csv")
wage = wage1.wage
educ = wage1.educ
coeff = (np.dot(educ.T,wage))/ (np.sum(np.square(educ)))
coeff


0.47266371884007347

In [8]:
## Question - 6
## Section - A

import pandas as pd
char = pd.read_csv("C:/Users/vamsh/Desktop/Python_Stats_Assignment/charity.csv")
a = np.average(char.gift)
a


7.4444704779756323

In [10]:
## Section - B

b = np.average(char.mailsyear)
b


2.0495548266166823

In [12]:
## Section - C

c = np.min(char.mailsyear)
c


0.25

In [18]:
## Section - D

char = pd.read_csv("C:/Users/vamsh/Desktop/Python_Stats_Assignment/charity.csv")
gift = char.gift
mailsyear = sm.add_constant(char.mailsyear)
r = sm.OLS(gift,mailsyear)
reg = r.fit()
reg.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   gift   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     59.65
Date:                Sun, 24 Apr 2016   Prob (F-statistic):           1.40e-14
Time:                        22:15:07   Log-Likelihood:                -17602.
No. Observations:                4268   AIC:                         3.521e+04
Df Residuals:                    4266   BIC:                         3.522e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const          2.0141      0.739      2.724      0.006         0.564     3.464
mailsyear      2.6495      0.343      7.723      0.000         1.977     3.322
==============================================================================
Omnibus:                     4951.411   Durbin-Watson:                   1.529
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           784986.187
Skew:                           5.889   Prob(JB):                         0.00
Kurtosis:                      68.387   Cond. No.                         8.34
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [48]:
## Section E

## We observe that the co-efficient of mailsyear is 2.6495
## We observe that this coefficient is positive
## Meaning : If this is increased, the gift value is also increases
## Per one unit increase, the gift will be increased by 2.6495
## If each mailing costs one guilder, the charity is expected to gain by a factor of 2.65 guilders
## Yes, the charity makes a net gain on every mailing (Since co-efficient is a positive value)

In [ ]:
## Section - F

## Even if there's no mailing, the value of gift is 2.01
## This means, the minimum amount of charity is always 2.01 
## This is the smallest predicted charitable contribution
## So, we can't predict zero for gift