In [8]:
import numpy as np
data = np.genfromtxt('C:/Users/vamsh/Desktop/Python/401K.csv',delimiter=',',skip_header = 1)

In [9]:
data

array([[  2.61000000e+01,   2.09999990e-01,   1.65300000e+03, ...,
          8.70900000e+03,   0.00000000e+00,   9.07211210e+00],
       [  1.00000000e+02,   1.42000000e+00,   2.62000000e+02, ...,
          3.15000000e+02,   1.00000000e+00,   5.75257250e+00],
       [  9.75999980e+01,   9.10000030e-01,   1.66000000e+02, ...,
          2.75000000e+02,   1.00000000e+00,   5.61677120e+00],
       ..., 
       [  1.00000000e+02,   2.27000000e+00,   1.92800000e+03, ...,
          2.17100000e+03,   0.00000000e+00,   7.68294330e+00],
       [  1.00000000e+02,   5.79999980e-01,   1.66000000e+02, ...,
          9.31000000e+02,   1.00000000e+00,   6.83625940e+00],
       [  1.00000000e+02,   4.49999990e-01,   2.17900000e+03, ...,
          3.18700000e+03,   0.00000000e+00,   8.06683540e+00]])

In [10]:
data.shape

(1534L, 8L)

In [49]:
Y = data[:,0].copy()
Y
Y = Y.reshape(1534,1)
Y
Y.shape

(1534L, 1L)

In [50]:
X = data[:,1].copy()
X
X = X.reshape(1534,1)
X.shape

(1534L, 1L)

In [51]:
X.shape

(1534L, 1L)

In [52]:
Y.shape

(1534L, 1L)

In [53]:
I = np.ones((1534,1))
I 
I.shape

(1534L, 1L)

In [54]:
X = np.concatenate((I,X),axis=1)
X
X.shape

(1534L, 2L)

In [55]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T,Y))
B

array([[ 83.07545543],
       [  5.8610792 ]])

In [57]:
E = Y - (np.dot(X,B))
E

array([[-58.206282  ],
       [  8.60181211],
       [  9.19096033],
       ..., 
       [  3.61989479],
       [ 13.52511875],
       [ 14.28705899]])

In [59]:
SSE = np.dot(E.T,E)
SSE

array([[ 396383.81240699]])